config/routes.rb
RosterApp::Application.routes.draw do
  resources :roles

  resources :employees
  resources :stores do
    resources :shifts
    resources :default_shifts
  end

  root to: 'stores#index'
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates_presence_of :dob , :first_name, :last_name, :role, :store_ids
  
  has_many :employments
  has_many :stores, through: :employments
  has_many :unavailabilities
  has_many :shifts
  accepts_nested_attributes_for :unavailabilities, allow_destroy: true
  accepts_nested_attributes_for :shifts
  
  ROLES = ['Employee', 'Shift Supervisor', 'Manager', 'Area Manager']
  RATES = [9.79, 10.94, 13.06, (15.18*1.09), (17.29*1.09), (19.72*1.09), (21.17*1.09), (21.99*1.09), (22.40*1.09), (25.00*1.09)] 
  
  
  
  def pay_rate
    case
    when supervisor?
      RATES[7]
    when manager?
      RATES[8]
    when area_manager?
      RATES[9]
    when age <= 15
      RATES[0]
    when age == 16
      RATES[1]
    when age == 17
      RATES[2]
    when age == 18
      RATES[3]
    when age == 19
      RATES[4]
    when age == 20
      RATES[5]
    when age >= 21
      RATES[6]
    end  
    
  end
  
  
  def supervisor?
    role == ROLES[1]
  end
    
  def manager?
    role == ROLES[2]
  end  
  
  def area_manager?
    role == ROLES[3]
  end   
      
  def age
      now = Time.now.utc.to_date
      now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end
    
  def find_or_initialize_shift_by_date(date)
    shifts.find_or_initialize_by_date
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_url }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to employees_url }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for @employee, html: {class: 'form'} do |f| %>

<% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 

  <%= hidden_field_tag "employee[store_ids][]", nil %>
  <% Store.all.each do |store| %>
    <%= label_tag do %>
      <%= check_box_tag "employee[store_ids][]", store.id, @employee.store_ids.include?(store.id), id: dom_id(store) %>
      <%= store.name %>
    <% end %>
  <% end %>
  
  <%= f.label :role %>
  <%= f.select :role, Employee::ROLES %>
  
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  
  <%= f.label :dob %>
  <%= f.date_select :dob, :order => [:day, :month, :year], start_year: Time.now.year - 70, end_year: Time.now.year - 12  %>
  
  <%= f.label :mobile %>
  <%= f.text_field :mobile %>
  
  <%= f.label :home_phone %>
  <%= f.text_field :home_phone %>
  
  <%= f.label :email %>
  <%= f.text_field :email %>
  
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  
  </button>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table class="table">
  <tr>
    <th>Role</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Dob</th>
    <th>Mobile</th>
    <th>Home phone</th>
    <th>Email</th>
    <th>Age</th>
    <th>Pay Rate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.role %></td>
    <td><%= employee.first_name %></td>
    <td><%= employee.last_name %></td>
    <td><%= employee.dob %></td>
    <td><%= employee.mobile %></td>
    <td><%= employee.home_phone %></td>
    <td><%= employee.email %></td>
    <td><%= employee.age %></td>
    <td><%= number_to_currency(employee.pay_rate) %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Role:</b>
  <%= @employee.role %>
</p>

<p>
  <b>First name:</b>
  <%= @employee.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @employee.last_name %>
</p>

<p>
  <b>Dob:</b>
  <%= @employee.dob %>
</p>

<p>
  <b>Mobile:</b>
  <%= @employee.mobile %>
</p>

<p>
  <b>Home phone:</b>
  <%= @employee.home_phone %>
</p>

<p>
  <b>Email:</b>
  <%= @employee.email %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>