config/routes.rb
RosterApp::Application.routes.draw do
  resources :roles

  resources :employees
  resources :stores do
    resources :shifts
    resources :default_shifts
  end

  root to: 'stores#index'
end

app/models/store.rb
class Store < ActiveRecord::Base
  validates_presence_of :address, :name

  has_many :shifts
  has_many :default_shifts
  has_many :employments
  has_many :employees, through: :employments

  accepts_nested_attributes_for :default_shifts, allow_destroy: true
  
 

  WEEK_START_DAY = 3

  def self.week_start_day_name
    Date::DAYNAMES[WEEK_START_DAY]
  end

  def self.next_week_start_day_date
    Chronic.parse("next #{week_start_day_name}").to_date
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    start_date = params[:start_date].blank? ? Store.next_week_start_day_date : Date.parse(params[:start_date])
    @dates = start_date..(start_date + 6.days)
    @employees = @store.employees.includes(:shifts).all
    @employees.each do |e|
      @dates.each do |date|
        e.shifts.find_or_initialize_by_date(date)
      end
      e.shifts.sort_by!(&:date)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to edit_store_path(@store), notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_default_shift_fields.html.erb
<li>
  <%= f.select :day, (0..6).map{ |i| [Date::DAYNAMES[i], i] } %>
  <%= f.text_field :start_time, class: 'input-small' %>
  <%= f.text_field :finish_time, class: 'input-small' %>
  <%= f.text_field :duty %>
  <%= f.text_field :notes %>
  <%= f.hidden_field :_destroy %>
  <%= link_to 'Delete', '#', class: 'remove_fields' %>
</li>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  

  <fieldset>
    <legend>Default shifts</legend>
    <ul>
      <%= f.fields_for :default_shifts do |builder| %>
      <%= render 'default_shift_fields', f: builder %>
      <% end %>
    </ul>
    <%= link_to_add_fields 'Add default shift', f, :default_shifts %>
  </fieldset>
  <br>
  
  <%= f.submit class: "btn btn-primary"%>
<% end %>
<br>
<br>

app/views/stores/edit.html.erb
<h1><%= @store.name %></h1>

<%= render 'form' %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stores.each do |store| %>
  <tr>
    <td><%= store.name %></td>
    <td><%= store.address %></td>
    <td><%= link_to 'Show', store %></td>
    <td><%= link_to 'Edit', edit_store_path(store) %></td>
    <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<h1><%= @store.name %> <small><%= link_to 'Edit', edit_store_path(@store) %></small></h1>
<table class="roster">  
  <tr>
    <td><%= link_to '<', store_url(@store, start_date: @dates.first - 7.days), class: 'btn btn-small prev pull-right' %></td>
      <% @dates.each do |date| %>
        <th><%=raw date.strftime('<span class="hday">%A</span><br>%d %b %y') %>
        <!-- <span class="label label-info">26%</span> -->
        </th>
        <% end %>
    <td><%= link_to '>', store_url(@store, start_date: @dates.first + 7.days), class: 'btn btn-small next pull-left' %></td>
  </tr>
  <tr>
    <td><span class="hday">
      Test</span><br><span class="hsurname">
      Employee</span>
    </td>
    <td>
      <div class="shift well">
        <span class="shift-time">7am - 3pm</span><br>
        <span class="shift-info">1/2hr break at 10am</span><br>
        <span class="badge badge-info pull-right">7.5</span><br>
        <span class="shift-info">OPEN</span><br>
        <span class="shift-info">FM, BV, Coke</span>
      </div>
    </td>
    <td>
      <div class="shift well">
        <span class="shift-time">7:30am - 3pm</span><br>
        <span class="shift-info">1/2hr break at 10am</span><br>
        <span class="badge badge-info pull-right">7.5</span><br>
        <span class="shift-info">OPEN</span><br>
        <span class="shift-info">FM, BV, Coke</span>
      </div>
    </td>
    <td>
      <div class="shift well">
        <span class="shift-time">7am - 3pm</span><br>
        <span class="shift-info">1/2hr break at 10am</span><br>
        <span class="badge badge-info pull-right">7.5</span><br>
        <span class="shift-info">OPEN</span><br>
        <span class="shift-info">FM, BV, Coke</span>
      </div>
    </td>
    <td>
      <div class="shift well">
        <span class="shift-time">7am - 2:30pm</span><br>
        <span class="shift-info">1/2hr break at 10am</span><br>
        <span class="badge badge-info pull-right">7</span><br>
        <span class="shift-info">OPEN</span><br>
        <span class="shift-info">FM, BV, Coke</span>
      </div>
    </td>
    <td>
      <div>
       
      </div>
    </td>
    <td>
      <div>
       
      </div>
    </td>
    <td>
      <div class="shift well">
        <span class="shift-time">3pm - 10:30pm</span><br>
        <span class="shift-info">1/2hr break at 3pm</span><br>
        <span class="badge badge-info pull-right">9</span><br>
        <span class="shift-info">OPEN</span><br>
        <span class="shift-info">FM, BV, Coke</span>
      </div>
    </td>
    <td></td>
  </tr>
  <% @employees.each do |employee| %>
      <tr>
        <td><span class="hday">
          <%= employee.first_name %></span><br><span class="hsurname">
          <%= employee.last_name %></span>
        </td>
        <%= render employee.shifts.select{ |s| s.date.in?(@dates) } %>
        <td></td>
      </tr>
  <% end %>
</table>