config/routes.rb
RosterApp::Application.routes.draw do
  resources :roles

  resources :employees
  resources :stores do
    resources :shifts
    resources :default_shifts
  end

  root to: 'stores#index'
end

app/models/default_shift.rb
class DefaultShift < ActiveRecord::Base
  belongs_to :store

  def start_time_finish_time
    "#{start_time}-#{finish_time}"
  end

  def start_time_finish_time_friendly
    "#{start_time.strftime('%l:%M %p')} - #{finish_time.strftime('%l:%M %p')}"
  end
end

app/controllers/default_shifts_controller.rb
class DefaultShiftsController < ApplicationController
  # GET /default_shifts
  # GET /default_shifts.json
  def index
    @default_shifts = DefaultShift.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @default_shifts }
    end
  end

  # GET /default_shifts/1
  # GET /default_shifts/1.json
  def show
    @default_shift = DefaultShift.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @default_shift }
    end
  end

  # GET /default_shifts/new
  # GET /default_shifts/new.json
  def new
    @default_shift = DefaultShift.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @default_shift }
    end
  end

  # GET /default_shifts/1/edit
  def edit
    @default_shift = DefaultShift.find(params[:id])
  end

  # POST /default_shifts
  # POST /default_shifts.json
  def create
    @default_shift = DefaultShift.new(params[:default_shift])

    respond_to do |format|
      if @default_shift.save
        format.html { redirect_to @default_shift, notice: 'Default shift was successfully created.' }
        format.json { render json: @default_shift, status: :created, location: @default_shift }
      else
        format.html { render action: "new" }
        format.json { render json: @default_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /default_shifts/1
  # PUT /default_shifts/1.json
  def update
    @default_shift = DefaultShift.find(params[:id])

    respond_to do |format|
      if @default_shift.update_attributes(params[:default_shift])
        format.html { redirect_to @default_shift, notice: 'Default shift was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @default_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /default_shifts/1
  # DELETE /default_shifts/1.json
  def destroy
    @default_shift = DefaultShift.find(params[:id])
    @default_shift.destroy

    respond_to do |format|
      format.html { redirect_to default_shifts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/default_shifts_helper.rb
module DefaultShiftsHelper
end

app/views/default_shifts/_form.html.erb
<%= form_for(@default_shift) do |f| %>
  <% if @default_shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@default_shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
        <% @default_shift.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :store_id %>
  <%= collection_select(:shift, :store_id, Store.all, :id, :name) %>

  <%= f.label :day %>
  <%= f.select :day, 0..6 %>

  <%= f.label :start_time %>
  <%= f.time_select :start_time, minute_step: 30, ampm: true %> 

  <%= f.label :finish_time %>
  <%= f.time_select :finish_time, minute_step: 30, ampm: true %>

  <%= f.label :break_time %>
  <%= f.time_select :break_time, minute_step: 30, ampm: true %>

  <%= f.label :duty %>
  <%= f.text_field :duty %>

  <%= f.label :notes %>
  <%= f.text_field :notes %>

  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/default_shifts/edit.html.erb
<h1>Editing default_shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @default_shift %> |
<%= link_to 'Back', default_shifts_path %>

app/views/default_shifts/index.html.erb
<h1>Listing default_shifts</h1>

<table>
  <tr>
    <th>Store</th>
    <th>Day</th>
    <th>Start time</th>
    <th>Finish time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @default_shifts.each do |default_shift| %>
  <tr>
    <td><%= default_shift.store_id %></td>
    <td><%= default_shift.day %></td>
    <td><%= default_shift.start_time %></td>
    <td><%= default_shift.finish_time %></td>
    <td><%= link_to 'Show', default_shift %></td>
    <td><%= link_to 'Edit', edit_default_shift_path(default_shift) %></td>
    <td><%= link_to 'Destroy', default_shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Default shift', new_default_shift_path %>

app/views/default_shifts/new.html.erb
<h1>New default_shift</h1>

<%= render 'form' %>

<%= link_to 'Back', default_shifts_path %>

app/views/default_shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Store:</b>
  <%= @default_shift.store_id %>
</p>

<p>
  <b>Day:</b>
  <%= @default_shift.day %>
</p>

<p>
  <b>Start time:</b>
  <%= @default_shift.start_time %>
</p>

<p>
  <b>Finish time:</b>
  <%= @default_shift.finish_time %>
</p>


<%= link_to 'Edit', edit_default_shift_path(@default_shift) %> |
<%= link_to 'Back', default_shifts_path %>