config/routes.rb
RosterApp::Application.routes.draw do
  resources :roles

  resources :employees
  resources :stores do
    resources :shifts
    resources :default_shifts
  end

  root to: 'stores#index'
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  belongs_to :employee
  belongs_to :store
  
  SHIFT_TYPE = ['Open', 'Close', 'Inventory', 'Wash Up']

  def dup 
    new_record = old_record.dup
  end

  def start_time_finish_time
    "#{start_time}-#{finish_time}"
  end

  def start_time_finish_time=(range)
    self.start_time, self.finish_time = range.split('-')
  end
  
  def start_time_finish_time_friendly
    # "#{start_time.strftime('%l:%M %p')} - #{finish_time.strftime('%l:%M %p')}"
  end
  
  def hours_worked
    ((finish_time - start_time) / 1.hour).round
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_filter :load_store

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = @store.shifts.new(params[:shift])

    respond_to do |format|
      if @shift.save
        format.html { redirect_to store_url(@store), notice: 'Shift was successfully created.' }
        format.json { render json: @shift, status: :created, location: @shift }
      else
        format.html { render action: "new" }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shifts/1
  # PUT /shifts/1.json
  def update
    @shift = @store.shifts.find(params[:id])

    respond_to do |format|
      if @shift.update_attributes(params[:shift])
        format.html { redirect_to store_url(@store), notice: 'Shift was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift = @store.shifts.find(params[:id])
    @shift.destroy

    respond_to do |format|
      format.html { redirect_to store_url(@store) }
      format.json { head :no_content }
    end
  end

  private

  def load_store
    @store = Store.find(params[:store_id])
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<%= form_for(@shift) do |f| %>
  <% if @shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% @shift.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :store_id %><br />
    <%= collection_select(:shift, :store_id, Store.all, :id, :name) %>
    
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.select :day, 0..6 %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.time_select :start_time, minute_step: 30, ampm: true %> 
  </div>
  <div class="field">
    <%= f.label :finish_time %><br />
    <%= f.time_select :finish_time, minute_step: 30, ampm: true %>
  </div>
  <div class="field">
    <%= f.label :break_time %><br />
    <%= f.time_select :break_time, minute_step: 30, ampm: true %>
  </div>
  <div class="field">
    <%= f.label :shift_type %><br />
    <%= f.text_field :shift_type %>
  </div>
  <div class="field">
    <%= f.label :orders_to_place %><br />
    <%= f.text_field :orders_to_place %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/shifts/_shift.html.erb
<td>
  <%= form_for [@store, shift] do |f| %>
    <%= f.hidden_field :employee_id %>
    <%= f.hidden_field :date %>
    <%= f.select :start_time_finish_time, @store.default_shifts.where(day: f.object.date.wday).map(&:start_time_finish_time), {include_blank: 'Shift'},  class: 'input-medium shift-range' %>
  <% end %>
</td>

app/views/shifts/edit.html.erb
<h1>Editing shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<h1>Standard shifts</h1>

<table class="table">
  <tr>
    <th>Store</th>
    <th>Day</th>
    <th>Shift</th>
    <th>Break time</th>
    <th>Shift type</th>
    <th>Orders to place</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
 

<% @shifts.each do |shift| %>
  <tr>
    <td><%= shift.store.name %></td>
    <td><%= shift.day %></td>
    <td><%= shift.start_time .strftime('%l:%M %p') %> - <%= shift.finish_time .strftime('%l:%M %p') %></td>
    <td><%= shift.break_time .strftime('%l:%M %p') %></td>
    <td><%= shift.shift_type %></td>
    <td><%= shift.orders_to_place %></td>
    <td><%= link_to 'Show', shift %></td>
    <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
    <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
   
<% end %>
</table>
<br />
<%= link_to 'New Shift', new_shift_path %>
<br />

app/views/shifts/new.html.erb
<h1>New shift</h1>

<%= render 'form' %>

<%= link_to 'Back', shifts_path %>

app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Store:</b>
  <%= @shift.store_id %>
</p>

<p>
  <b>Day:</b>
  <%= @shift.day %>
</p>

<p>
  <b>Start time:</b>
  <%= @shift.start_time %>
</p>

<p>
  <b>Finish time:</b>
  <%= @shift.finish_time %>
</p>

<p>
  <b>Break time:</b>
  <%= @shift.break_time %>
</p>

<p>
  <b>Shift type:</b>
  <%= @shift.shift_type %>
</p>

<p>
  <b>Orders to place:</b>
  <%= @shift.orders_to_place %>
</p>


<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>